---
- name: Update web servers
  hosts: webservers
  become: true

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: present

- name: Update web servers
  hosts: tyme-4-lb-1-test ansible_user=vagrant
  become: true